services:
    nextjs:
        build: .
        ports:
            - "80:3000"
        environment:
            - DATABASE_URL=${DATABASE_URL}
            - SHADOW_DATABASE_URL=${SHADOW_DATABASE_URL}
            - AUTH_SECRET=${AUTH_SECRET}
            - AUTH_GITHUB_ID=${AUTH_GITHUB_ID}
            - AUTH_GITHUB_SECRET=${AUTH_GITHUB_SECRET}
            - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
            - AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}
